api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        html:     ['text/html']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
#        versions: [3]
    enable_swagger_ui: true
    enable_re_doc: true
